### ISSUE TITLE
mp3 

### ISSUE THREAD

**Issue by grumpi** [citronalco/FM4-7Tage-Download#1]
the download continues after downloading all parts of a show.
the playback of the downloaded mp3s is way too fast.

**Comment by citronalco** [comment]
I guess you're using Windows? If yes the script should work much better with the latest changes. Could you please try?

As the script just downloads the mp3 files from FM4 and does not modify them (except the tag info) I can't do anything about your playback issue.

**Comment by citronalco** [comment]
I assume it works now for you. If it doesn't just let me know.
