### ISSUE TITLE
Stream adress changed

### ISSUE THREAD

**Issue by tonwelle** [citronalco/FM4-7Tage-Download#3]
The downloader script  is not working anymore due to an address change on the fm4 loopstream server.
The new shoutcastBaseURL is `https://loopstreamfm4.apa.at/?channel=fm4&id=%s `
Note the switch to https.
Thanks for the amazing script. Working flawless here for quiet some time!

**Comment by citronalco** [comment]
Thanks, fixed! (https://github.com/citronalco/FM4-7Tage-Download/commit/07f7d96d026256325b65f83a5fdca6fb736f73ef)
